### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by ndobb** [MattTriano/postgis_geocoder#6]
Hey @MattTriano  - this is awesome work! If I'm reading through the code correctly, you've built out and significantly expanded [my current geocoder repo](https://github.com/uwrit/postgis-docker/). Let me know if I'm misunderstanding.

If that's the case, while my repo is MIT-licensed, I'd still appreciate a minimal mention of attribution somewhere given that my code likely saved you a bundle of time, and is still being used in quite a few places, at a glance, despite this not technically being a fork.

Thanks,
-nic

**Comment by MattTriano** [comment]
Hey Nic, thanks for adapting the [PostGIS data loading sql scripts](https://git.osgeo.org/gitea/postgis/postgis/src/branch/master/extras/tiger_geocoder/tiger_loader_2019.sql) this [shell script](https://github.com/uwrit/postgis-docker/blob/master/src/db/load_data.sh) format. I learned a lot about bash scripting getting to a solution that reliably pulls and loads all of the Census TIGER data. When I was using your download-data-during-initialization strategy, after a few hours of downloading and ingesting data, some network request would fail and the process would short circuit, forcing me to delete the volume, wait a day for the Census's bandwidth checks to reset, and try again. It took me a couple of months to transform the strategy into one that reliably succeeds, and if I have cause to work with this again, I'll embrace [Google's bash scripting guidance](https://google.github.io/styleguide/shellguide.html#when-to-use-shell) "If you are writing a script that is more than 100 lines long, or that uses non-straightforward control flow logic, you should rewrite it in a more structured language now. Bear in mind that scripts grow. Rewrite your script early to avoid a more time-consuming rewrite at a later date."

Anyway, I gave you a mention in this project's README, and without your work, I wouldn't have found and read the GNU GPLv2 licensed [source code](https://git.osgeo.org/gitea/postgis/postgis/src/branch/master/extras/tiger_geocoder/tiger_loader_2019.sql) that I believe was the basis for the file of yours that I referenced (hence my use of the [GNU GPLv2 license](https://git.osgeo.org/gitea/postgis/postgis/src/branch/master/COPYING#L98). 

Let me know if I was mistaken and your work isn't derived from the [PostGIS tiger_loader_YYYY.sql scripts](https://git.osgeo.org/gitea/postgis/postgis/src/branch/master/extras/tiger_geocoder) and I'll look into adding on an MIT license to my repo in addition to the GNU GPLv2 license.
Thanks,
Matt
